services:
  telegram_bot:
    build: .
    restart: always
    container_name: uchet_bot
    command: /bin/sh -c "alembic upgrade head && python -m app.bot.init"
    ports:
      - "2432:2432"
    env_file:
      - .env
    depends_on:
      - db
      
  flask_admin:
    build: .
    restart: always
    container_name: flask_admin
    command:  python -m app.flask_admin.app 
    ports:
      - "2434:2434"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: uchet
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_LOG_CONNECTIONS: on
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - "5432:5432"
    

volumes:
  pgdata:
networks:
  app_network:
    driver: bridge