"""fix

Revision ID: 5f93e77aaacf
Revises: e3445c38ca11
Create Date: 2025-06-08 08:23:41.837325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f93e77aaacf'
down_revision: Union[str, None] = 'e3445c38ca11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column(
    #     'materials',
    #     sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('1'))
    # )
    # Удаляем creator_id и constraint через batch_alter_table
    with op.batch_alter_table('objects') as batch_op:
        batch_op.drop_column('creator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('objects') as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.BIGINT(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['creator_id'], ['telegram_id'])
    op.drop_column('materials', 'is_active')
