"""add profit accounting tables

Revision ID: 976279508bff
Revises: 62e2eeb2710e
Create Date: 2025-06-24 04:01:15.040086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '976279508bff'
down_revision: Union[str, None] = '62e2eeb2710e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_profic_accounting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('profic_accounting_object_id_fkey', 'profic_accounting', type_='foreignkey')
    op.drop_column('profic_accounting', 'object_id')
    op.create_unique_constraint(None, 'users', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('profic_accounting', sa.Column('object_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('profic_accounting_object_id_fkey', 'profic_accounting', 'objects', ['object_id'], ['id'], ondelete='CASCADE')
    op.drop_table('object_profic_accounting')
    # ### end Alembic commands ###
