"""fix

Revision ID: c8a8ef76d1be
Revises: fd61823052ac
Create Date: 2025-07-12 17:51:07.882331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.db.models import ObjectDocument


# revision identifiers, used by Alembic.
revision: str = 'c8a8ef76d1be'
down_revision: Union[str, None] = 'fd61823052ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object_documents', sa.Column('document_file_type', sa.String(length=20), nullable=False, default=ObjectDocument.DocumentFileType.pdf.value))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object_documents', 'document_file_type')
    # ### end Alembic commands ###
